### ISSUE TITLE
List of Issues, Forge: 1.0.0

### ISSUE THREAD

**Issue by Drackion** [GregTechCEu/GregTech-Modern#1]
Version: 1.0.0 (forge)

Mods:
- Ae2 12.9.2
- Architectury 6.5.69
- Cloth config 8.2.88
- kubejs 1902.6.0-build.142
- lazydfu 1.0.2
- oculus 1.2.8a
- REI Pulgin Compat 9.0.48
- rhino 1902.2.2-build.264
- REI 9.1.595
- rubidium 0.6.2
- rubidium extra 0.4.17 (build.71)
- TexTrueRubidiumOptions 1.02
- TOP 6.2.2

 Issues: 
- [x] Only empty fluid cells are visible in JEI and Minecraft search
- [x] (REI) when viewing a recipe Left and Right click don't work for checking the uses or recipes for the ingredients but "R" and "U" still work, this only affects items 
- [x] `Machines void item contents when broken` NULL JUST SKILL ISSUE
- [x] (REI) Left and Right click don't work for checking the recipes and uses of gtceu fluids when checking from the REI search
- [ ] (AE2 & REI) Only GTECu fluids are recognised when using the "+" in REI to auto fill processing patterns
- [x] Blocks loose their NBT data when broken, e.g. mining coke bricks give "casing" and not "coke bricks"
- [x] Steam boilers (single block) can't be filled with water via a water bucket and water cells, (Irgendwer)
- [x] Laminated Glass allows for xray

**Comment by Yefancy** [comment]
Machines void item contents when broken
 what machine? actually, it wont drop if you re in a creative mode. only survival mode will drop contents

**Comment by Drackion** [comment]
ok so it was just skill issue
