### ISSUE TITLE
Deepslate Ores not Generating?

### ISSUE THREAD

**Issue by nekomaster** [GregTechCEu/GregTech-Modern#116]
### GregTech CEu Version

Forge 1.0.4 (June 22nd 2023)

### Recipe Viewer Installed

JEI

### Environment

Singleplayer

### Cross-Mod Interaction

Unsure

### Expected Behavior

I expect to see ores generating below layer 0 such as GTCEu 1.19's deep slate ores I see in Creative/JEI Search.

### Actual Behavior

Deepslate and Tuff do not generate any of GT's Ores, only mineraft ores show up in deepslate.
Only GTCEu ores that generate below layer 0 are any that happen to be in a stone, diorite, granite or andesite vein that happens to dip below layer 0 (which isn't often from what I see)

### Steps to Reproduce

Setup: 
Windows 11 2H22 x64
OpenJDK 17U hotspot 17.0.7_7
Minecraft Forge 43.2.13

geceu-forge-1.19.2-1.0.4.jar
jade-1.19.1-forge.8.8.0.jar
jei-1.19.2-forge-11.6.0.1015.jar
journeymap-1.19.2-5.9.7-forge.jar
JustEnoughResources-1.19.2-1.1.0.179.jar
worldedit-mod-7.2.12.jar

Launch game, goto single player and generate a new default biome size world with structures enabled, and explore many chunks of deepslate (worldedit is handy here to quickly bore tunnels through the ground with the /br sphere air <radius> command to quickly uncover ore veins)

You should see that below layer 0 no GT deepslate or tuff ores appear.

### Additional Information

Either the generation for deepslate and tuff ores are bugged, or its not coded yet

(PS, I apologise if my bug report is sub-standard and/or if this is a known issue by the devs)

**Comment by screret** [comment]
Correct
They don't exist _yet_

We'll reorganize the worldgen soonTM but it hasn't happened yet

**Comment by screret** [comment]
this feature has been done.
