### ISSUE TITLE
Phase through pipes when equip a wrench.

### ISSUE THREAD

**Issue by 34486** [GregTechCEu/GregTech-Modern#123]
### GregTech CEu Version

1.0.5_20

### Recipe Viewer Installed

JEI

### Environment

Singleplayer

### Cross-Mod Interaction

Unsure

### Expected Behavior

Not phase through pipes when I equip a wrench in hand.

### Actual Behavior

Phase through pipes when I equip wrench in hand.

### Steps to Reproduce

Stand on top of a pipe, then select a wrench to be in your hand, you will fall into/through the pipe you are standing on. 

### Additional Information

n/a?

**Comment by Yefancy** [comment]
well, it not actually a bug. To do so on purpose,

**Comment by screret** [comment]
i don't think that should be a feature.
