### ISSUE TITLE
GT sword not consider a "sword" tool when breaking cobweb

### ISSUE THREAD

**Issue by GuiLaroche** [GregTechCEu/GregTech-Modern#1540]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

Latest

### Recipe Viewer Installed

None

### Environment

Singleplayer

### Cross-Mod Interaction

No

### Other Installed Mods

Its a modpack, so a lot, but I'm pretty sure the bug dont come from them.

(Sword from other mods doesnt have the issue.)

### Expected Behavior

Cobweb block should be able to be mine and drop string when destroy using a gt sword.

### Actual Behavior

The cobweb break slowly and doesnt drop anything.

### Steps to Reproduce

1. Place a cobweb.
2. Try to mine it with any gt sword.

### Additional Information

I saw this for cobweb but I think the issue may be the same for any block at require a sword to break.

**Comment by screret** [comment]
"latest" isn't very descriptive. what MC version, for example?
