### ISSUE TITLE
Addition of a few more tabs

### ISSUE THREAD

**Issue by stanieldev** [GregTechCEu/GregTech-Modern#166]
### Feature Description

 - A few suggestions I have:
 - Separate Ores from Frames and Blocks
 - Separate Wires from Pipes
 - A Multiblocks Section that include blocks in multiblocks + Multiblock Controllers
    - Separated from single machines.
 - Put the batteries in the tools section.
 
The new tabs I'm suggesting all together is:
 - Material Fluids
 - Material Items (include turbine fans in here)
 - Material Blocks
 - Material Ores
 - Material Fluid Pipes
 - Material Cables
 - GregTech Tools
 - GregTech Machines
 - GregTech Multiblocks
 - Gregtech Items

**Comment by screret** [comment]
too many tabs.
