### ISSUE TITLE
Issue with GT blocks and Timber Frames/Braces from Supplementaries

### ISSUE THREAD

**Issue by ChromaPIE** [GregTechCEu/GregTech-Modern#51]
### GregTech CEu Version

v1.0.2

### Recipe Viewer Installed

REI

### Environment

Not related

### Cross-Mod Interaction

Yes

### Expected Behavior

Timber Frames/Braces from Supplementaries shows GT blocks inserted with correct textures and colors.

Like: (Redstone Block)
<img src="https://user-images.githubusercontent.com/56111366/229701613-7fb6c081-230d-44d2-af58-e0eec392c228.png" width="683" height="384"/>

### Actual Behavior

Before:
<img src="https://user-images.githubusercontent.com/56111366/229700309-bc9b21d7-3a1b-4243-b53d-ec3710bce960.png" width="683" height="384"/>

After: (Tested with several GT ores and material storage blocks)
<img src="https://user-images.githubusercontent.com/56111366/229700762-2415cbb3-e2f7-48bc-ba5f-a544fbc92b8c.png" width="683" height="384"/>

### Steps to Reproduce

See the screenshots above.

**Comment by screret** [comment]
E.g. [this mixin](https://github.com/Low-Drag-MC/LDLib-Architectury/blob/f3e68d10f72f2ea75567853e0051ad34403e35c6/fabric/src/main/java/com/lowdragmc/lowdraglib/fabric/core/mixins/BlockModelShaperMixin.java) should also exist for `getMaterials`

**Comment by screret** [comment]
should be fixed with #529.
