### ISSUE TITLE
Crash Upon Start-Up with Quilt

### ISSUE THREAD

**Issue by ChaosDogG** [GregTechCEu/GregTech-Modern#72]
### GregTech CEu Version

1.0.3

### Recipe Viewer Installed

No Recipe Viewer

### Environment

Start-Up

### Cross-Mod Interaction

Unsure

### Expected Behavior

The game to load

### Actual Behavior

Crashes on start-up
[Angry at REI](https://github.com/GregTechCEu/GregTechCEu-1.19/files/11468123/crash-2023-05-12_15.16.45-client.txt)
[Angry at REI](https://github.com/GregTechCEu/GregTechCEu-1.19/files/11468124/crash-2023-05-12_15.18.30-client.txt)
[Angry at Dimensional Doors](https://github.com/GregTechCEu/GregTechCEu-1.19/files/11468125/crash-2023-05-12_15.20.58-client.txt)
[Angry at Create](https://github.com/GregTechCEu/GregTechCEu-1.19/files/11468126/crash-2023-05-12_15.23.58-client.txt)
[Angry at GregTech](https://github.com/GregTechCEu/GregTechCEu-1.19/files/11468127/crash-2023-05-12_15.26.45-client.txt)

### Steps to Reproduce

Load the game with several mods
Witness it throw a fit

**Comment by DStrand1** [comment]
Looks like there are still issues with Quilt, will investigate

**Comment by unix-supremacist** [comment]
quilt is very 🔰 compat issues is likely on their side and not yours, though i can say that dimdoors and lowdraglib do not like each other even on fabric

**Comment by ChaosDogG** [comment]
is it exclusively those two?

**Comment by Yefancy** [comment]
crash log?

**Comment by ChaosDogG** [comment]
[crash-2023-06-15_14.13.59-client.txt](https://github.com/GregTechCEu/GregTechCEu-1.19/files/11763404/crash-2023-06-15_14.13.59-client.txt)
[latest.log](https://github.com/GregTechCEu/GregTechCEu-1.19/files/11763405/latest.log)
Here are some relevant files concerning this issue

**Comment by Yefancy** [comment]
we haven't supported quilt yet

**Comment by ChaosDogG** [comment]
well it says on the release that it is-

**Comment by screret** [comment]
fabric is deead, fabric is dee-ee-eeaaad
